eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://mysql-db-instance.ct06e24242ry.eu-west-2.rds.amazonaws.com:3306/userdb
    username: admin
    password: adminadmin
